server:
  port: 8080

spring:
  application:
    name: api-gateway

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://keycloak:9090/realms/biblioteca-realm1
        registration:
          biblio-client:
            client-id: biblio-client
            client-secret: TU_SECRET
            scope: openid,profile,email

      resourceserver:
        jwt:
          issuer-uri: http://keycloak:9090/realms/biblioteca-realm1

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: false

      default-filters:
        - TokenRelay

      routes:
        - id: ms-loan-route
          uri: lb://MS-LOAN
          predicates:
            - Path=/MS-LOAN/**
          filters:
            - StripPrefix=1

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Loan Service API
        url: /MS-LOAN/v3/api-docs

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
