server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        # Ruta principal del microservicio ms-loan
        - id: ms-loan
          uri: lb://ms-loan
          predicates:
            - Path=/ms-loan/**
          filters:
            - StripPrefix=1

        # ⚠️ Ruta específica para swagger de ms-loan
        - id: ms-loan-swagger
          uri: lb://ms-loan
          predicates:
            - Path=/ms-loan/v3/api-docs
          filters:
            - StripPrefix=1

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Loan Service API
        url: /ms-loan/v3/api-docs

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "health,info,*"
