spring:
  application:
    name: discovery-server
  config:
    import: optional:configserver:http://config-server:8888

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
